In [70]:
# Downloading Dataset

import kagglehub

# Download latest version

import os

os.makedirs("data", exist_ok=True)

path = kagglehub.dataset_download("brsahan/vehicle-co2-emissions-dataset")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Anand Murthy\.cache\kagglehub\datasets\brsahan\vehicle-co2-emissions-dataset\versions\1

In [71]:
path

'C:\\Users\\Anand Murthy\\.cache\\kagglehub\\datasets\\brsahan\\vehicle-co2-emissions-dataset\\versions\\1'

In [72]:
import pandas as pd
import numpy as np

emissions = pd.read_csv(path + "/co2.csv")
emissions.head()

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [73]:
emissions.info()

<class 'pandas.DataFrame'>
RangeIndex: 7385 entries, 0 to 7384
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Make                              7385 non-null   str
 1   Model                             7385 non-null   str
 2   Vehicle Class                     7385 non-null   str
 3   Engine Size(L)                    7385 non-null   float64
 4   Cylinders                         7385 non-null   int64
 5   Transmission                      7385 non-null   str
 6   Fuel Type                         7385 non-null   str
 7   Fuel Consumption City (L/100 km)  7385 non-null   float64
 8   Fuel Consumption Hwy (L/100 km)   7385 non-null   float64
 9   Fuel Consumption Comb (L/100 km)  7385 non-null   float64
 10  Fuel Consumption Comb (mpg)       7385 non-null   int64
 11  CO2 Emissions(g/km)               7385 non-null   int64
dtypes: float64(4), int64(3), str(5)
memory usage: 692.5 KB

In [74]:
emissions.describe().T

,count,mean,std,min,25%,50%,75%,max
Engine Size(L),7385.0,3.160068,1.354170,0.9,2.0,3.0,3.7,8.4
Cylinders,7385.0,5.615030,1.828307,3.0,4.0,6.0,6.0,16.0
Fuel Consumption City (L/100 km),7385.0,12.556534,3.500274,4.2,10.1,12.1,14.6,30.6
Fuel Consumption Hwy (L/100 km),7385.0,9.041706,2.224456,4.0,7.5,8.7,10.2,20.6
Fuel Consumption Comb (L/100 km),7385.0,10.975071,2.892506,4.1,8.9,10.6,12.6,26.1
Fuel Consumption Comb (mpg),7385.0,27.481652,7.231879,11.0,22.0,27.0,32.0,69.0
CO2 Emissions(g/km),7385.0,250.584699,58.512679,96.0,208.0,246.0,288.0,522.0

In [75]:
emissions.nunique()

Make                                  42
Model                               2053
Vehicle Class                         16
Engine Size(L)                        51
Cylinders                              8
Transmission                          27
Fuel Type                              5
Fuel Consumption City (L/100 km)     211
Fuel Consumption Hwy (L/100 km)      143
Fuel Consumption Comb (L/100 km)     181
Fuel Consumption Comb (mpg)           54
CO2 Emissions(g/km)                  331
dtype: int64

In [76]:
veh_classes = emissions["Vehicle Class"].unique()
veh_classes

<StringArray>
[                 'COMPACT',              'SUV - SMALL',
                 'MID-SIZE',               'TWO-SEATER',
              'MINICOMPACT',               'SUBCOMPACT',
                'FULL-SIZE',    'STATION WAGON - SMALL',
           'SUV - STANDARD',              'VAN - CARGO',
          'VAN - PASSENGER',  'PICKUP TRUCK - STANDARD',
                  'MINIVAN',  'SPECIAL PURPOSE VEHICLE',
 'STATION WAGON - MID-SIZE',     'PICKUP TRUCK - SMALL']
Length: 16, dtype: str

In [77]:
# Simplifying the vehicle class names by removing spaces and hyphens, and converting to lowercase for easier handling in code.
veh_classes_rename = {
    veh_class : veh_class.replace(" ", "").replace("-","_").lower() for veh_class in veh_classes
}
veh_classes_rename

{'COMPACT': 'compact',
 'SUV - SMALL': 'suv_small',
 'MID-SIZE': 'mid_size',
 'TWO-SEATER': 'two_seater',
 'MINICOMPACT': 'minicompact',
 'SUBCOMPACT': 'subcompact',
 'FULL-SIZE': 'full_size',
 'STATION WAGON - SMALL': 'stationwagon_small',
 'SUV - STANDARD': 'suv_standard',
 'VAN - CARGO': 'van_cargo',
 'VAN - PASSENGER': 'van_passenger',
 'PICKUP TRUCK - STANDARD': 'pickuptruck_standard',
 'MINIVAN': 'minivan',
 'SPECIAL PURPOSE VEHICLE': 'specialpurposevehicle',
 'STATION WAGON - MID-SIZE': 'stationwagon_mid_size',
 'PICKUP TRUCK - SMALL': 'pickuptruck_small'}

In [78]:
emissions["Vehicle Class"] = emissions["Vehicle Class"].replace(veh_classes_rename)

In [79]:
emissions.info()

<class 'pandas.DataFrame'>
RangeIndex: 7385 entries, 0 to 7384
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Make                              7385 non-null   str
 1   Model                             7385 non-null   str
 2   Vehicle Class                     7385 non-null   str
 3   Engine Size(L)                    7385 non-null   float64
 4   Cylinders                         7385 non-null   int64
 5   Transmission                      7385 non-null   str
 6   Fuel Type                         7385 non-null   str
 7   Fuel Consumption City (L/100 km)  7385 non-null   float64
 8   Fuel Consumption Hwy (L/100 km)   7385 non-null   float64
 9   Fuel Consumption Comb (L/100 km)  7385 non-null   float64
 10  Fuel Consumption Comb (mpg)       7385 non-null   int64
 11  CO2 Emissions(g/km)               7385 non-null   int64
dtypes: float64(4), int64(3), str(5)
memory usage: 692.5 KB

In [80]:
emissions["Make"].unique()

<StringArray>
[        'ACURA',    'ALFA ROMEO',  'ASTON MARTIN',          'AUDI',
       'BENTLEY',           'BMW',         'BUICK',      'CADILLAC',
     'CHEVROLET',      'CHRYSLER',         'DODGE',          'FIAT',
          'FORD',           'GMC',         'HONDA',       'HYUNDAI',
      'INFINITI',        'JAGUAR',          'JEEP',           'KIA',
   'LAMBORGHINI',    'LAND ROVER',         'LEXUS',       'LINCOLN',
      'MASERATI',         'MAZDA', 'MERCEDES-BENZ',          'MINI',
    'MITSUBISHI',        'NISSAN',       'PORSCHE',           'RAM',
   'ROLLS-ROYCE',         'SCION',         'SMART',           'SRT',
        'SUBARU',        'TOYOTA',    'VOLKSWAGEN',         'VOLVO',
       'GENESIS',       'BUGATTI']
Length: 42, dtype: str

In [81]:
emissions["Make"] = emissions["Make"].str.lower().replace(r"[^a-zA-Z0-9]", "_", regex=True)

In [82]:
emissions["Make"].unique()

<StringArray>
[        'acura',    'alfa_romeo',  'aston_martin',          'audi',
       'bentley',           'bmw',         'buick',      'cadillac',
     'chevrolet',      'chrysler',         'dodge',          'fiat',
          'ford',           'gmc',         'honda',       'hyundai',
      'infiniti',        'jaguar',          'jeep',           'kia',
   'lamborghini',    'land_rover',         'lexus',       'lincoln',
      'maserati',         'mazda', 'mercedes_benz',          'mini',
    'mitsubishi',        'nissan',       'porsche',           'ram',
   'rolls_royce',         'scion',         'smart',           'srt',
        'subaru',        'toyota',    'volkswagen',         'volvo',
       'genesis',       'bugatti']
Length: 42, dtype: str

In [83]:
emissions

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,acura,ILX,compact,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,acura,ILX,compact,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,acura,ILX HYBRID,compact,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,acura,MDX 4WD,suv_small,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,acura,RDX AWD,suv_small,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,volvo,XC40 T5 AWD,suv_small,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,volvo,XC60 T5 AWD,suv_small,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,volvo,XC60 T6 AWD,suv_small,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,volvo,XC90 T5 AWD,suv_standard,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,volvo,XC90 T6 AWD,suv_standard,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

In [84]:
emissions.drop(columns=["Model"], inplace=True) # does not matter to our analysis
# emissions.drop(columns=["Transmission"], inplace=True) # Yet to review if this is useful for analysis

In [85]:
emissions

,Make,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,acura,compact,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,acura,compact,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,acura,compact,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,acura,suv_small,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,acura,suv_small,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...
7380,volvo,suv_small,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,volvo,suv_small,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,volvo,suv_small,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,volvo,suv_standard,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,volvo,suv_standard,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

In [86]:
emissions.rename(
    columns= {
        "Vehicle Class": "Vehicle_type",
        "Engine Size(L)": "Engine_size_L",
        "Fuel Type": "Fuel_type",
        "Fuel Consumption City (L/100 km)": "Fuel_consumption_city_L_per_100km",
        "Fuel Consumption Hwy (L/100 km)": "Fuel_consumption_hwy_L_per_100km",
        "Fuel Consumption Comb (L/100 km)": "Fuel_consumption_comb_L_per_100km",
        "Fuel Consumption Comb (mpg)": "Fuel_consumption_comb_mpg",
        "CO2 Emissions(g/km)": "CO2_emissions_g_per_km"
    },
    inplace=True
)

In [87]:
emissions

,Make,Vehicle_type,Engine_size_L,Cylinders,Transmission,Fuel_type,Fuel_consumption_city_L_per_100km,Fuel_consumption_hwy_L_per_100km,Fuel_consumption_comb_L_per_100km,Fuel_consumption_comb_mpg,CO2_emissions_g_per_km
0,acura,compact,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,acura,compact,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,acura,compact,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,acura,suv_small,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,acura,suv_small,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...
7380,volvo,suv_small,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,volvo,suv_small,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,volvo,suv_small,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,volvo,suv_standard,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,volvo,suv_standard,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

In [88]:
emissions.info()

<class 'pandas.DataFrame'>
RangeIndex: 7385 entries, 0 to 7384
Data columns (total 11 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Make                               7385 non-null   str
 1   Vehicle_type                       7385 non-null   str
 2   Engine_size_L                      7385 non-null   float64
 3   Cylinders                          7385 non-null   int64
 4   Transmission                       7385 non-null   str
 5   Fuel_type                          7385 non-null   str
 6   Fuel_consumption_city_L_per_100km  7385 non-null   float64
 7   Fuel_consumption_hwy_L_per_100km   7385 non-null   float64
 8   Fuel_consumption_comb_L_per_100km  7385 non-null   float64
 9   Fuel_consumption_comb_mpg          7385 non-null   int64
 10  CO2_emissions_g_per_km             7385 non-null   int64
dtypes: float64(4), int64(3), str(4)
memory usage: 634.8 KB

In [89]:
emissions["Fuel_type"].unique()

<StringArray>
['Z', 'D', 'X', 'E', 'N']
Length: 5, dtype: str

In [90]:
emissions["Fuel_type"] = emissions["Fuel_type"].replace(
    {
        "X": "gasoline",
        "Z": "electricity",
        "D": "diesel",
        "E": "ethanol",
        "N": "natural gas"
    }
)

In [91]:
emissions["Fuel_type"]

0       electricity
1       electricity
2       electricity
3       electricity
4       electricity
           ...
7380    electricity
7381    electricity
7382    electricity
7383    electricity
7384    electricity
Name: Fuel_type, Length: 7385, dtype: str

In [92]:
emissions.duplicated().sum()

np.int64(2171)

In [93]:
emissions.shape

(7385, 11)

In [94]:
emissions.drop_duplicates(inplace=True)

In [95]:
emissions.duplicated().sum()

np.int64(0)

In [96]:
emissions

,Make,Vehicle_type,Engine_size_L,Cylinders,Transmission,Fuel_type,Fuel_consumption_city_L_per_100km,Fuel_consumption_hwy_L_per_100km,Fuel_consumption_comb_L_per_100km,Fuel_consumption_comb_mpg,CO2_emissions_g_per_km
0,acura,compact,2.0,4,AS5,electricity,9.9,6.7,8.5,33,196
1,acura,compact,2.4,4,M6,electricity,11.2,7.7,9.6,29,221
2,acura,compact,1.5,4,AV7,electricity,6.0,5.8,5.9,48,136
3,acura,suv_small,3.5,6,AS6,electricity,12.7,9.1,11.1,25,255
4,acura,suv_small,3.5,6,AS6,electricity,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...
7380,volvo,suv_small,2.0,4,AS8,electricity,10.7,7.7,9.4,30,219
7381,volvo,suv_small,2.0,4,AS8,electricity,11.2,8.3,9.9,29,232
7382,volvo,suv_small,2.0,4,AS8,electricity,11.7,8.6,10.3,27,240
7383,volvo,suv_standard,2.0,4,AS8,electricity,11.2,8.3,9.9,29,232
7384,volvo,suv_standard,2.0,4,AS8,electricity,12.2,8.7,10.7,26,248

In [98]:
emissions.to_csv("../../data/emissions_cleaned.csv")